runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main
api_version: 1
threadsafe: true

runtime_config:
  python_version: 3

handlers:
- url: project/static
  static_dir: project/static
- url: /.*
  script: main.app

skip_files:
- .git/
